import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "FairRent terms of service. Understand the terms of using our free rent analysis tools.",
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <h1 className="text-3xl font-bold text-[#1c1917] mb-8">Terms of Service</h1>
      <p className="text-sm text-[#a8a29e] mb-8">Last updated: March 19, 2026</p>

      <div className="prose prose-stone max-w-none space-y-6 text-[#57534e] text-sm leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">1. Acceptance of Terms</h2>
          <p>By accessing and using FairRent (fairrent.app), you agree to these Terms of Service. If you do not agree, please do not use our services.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">2. Description of Service</h2>
          <p>FairRent provides free rent analysis tools, market data, and tenant resources. Our services include rent fairness scoring, market comparisons, negotiation letter generation, and building intelligence.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">3. Important Disclaimer</h2>
          <p className="font-medium text-[#1c1917]">FairRent provides data and tools for informational purposes only. Our services do not constitute financial, legal, or real estate advice.</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Rent estimates and fairness scores are based on available market data and may not reflect your exact situation</li>
            <li>Negotiation letters generated by our tools are templates, not legal documents. We recommend reviewing them with a qualified professional</li>
            <li>Building violation data and landlord ratings are sourced from public records and may not be complete or current</li>
            <li>We are not responsible for decisions made based on information provided by our tools</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">4. Data Accuracy</h2>
          <p>While we strive to provide accurate and up-to-date information, we cannot guarantee the accuracy, completeness, or timeliness of all data. Market conditions change frequently, and our data sources may have inherent limitations. Always verify important information independently before making housing decisions.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">5. User Conduct</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Use our services for any unlawful purpose</li>
            <li>Attempt to scrape, copy, or redistribute our data without permission</li>
            <li>Interfere with the proper functioning of the service</li>
            <li>Misrepresent generated content as professional legal or financial advice</li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">6. Intellectual Property</h2>
          <p>All content, design, and functionality of FairRent are owned by FairRent and are protected by applicable intellectual property laws. Government data used in our analysis is in the public domain.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">7. Limitation of Liability</h2>
          <p>FairRent is provided &quot;as is&quot; without warranties of any kind. We shall not be liable for any damages arising from your use of the service, including but not limited to direct, indirect, incidental, or consequential damages.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">8. Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of FairRent after changes constitutes acceptance of the new terms.</p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-[#1c1917] mb-3">9. Contact</h2>
          <p>For questions about these terms, contact us at legal@fairrent.app.</p>
        </section>
      </div>
    </div>
  );
}
